# Generated by Django 5.0.4 on 2024-06-05 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 5, 7, 20, 45, 333871, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
